menu = [{'name': 'Add Student', 'url': '/add_student', 'icon': 'add_circle'}, 
        # {'name': 'Add Faculty', 'url': '/add_faculty', 'icon': 'person_add'}, 
        {'name': 'Add Course', 'url': '/add_course', 'icon': 'school'}, 
        {'name': 'Add Subject', 'url': '/add_subject', 'icon': 'subject'}, 
        {'name': 'Add Exam', 'url': '/add_exam', 'icon': 'assignment'}, 
        # {'name': 'Add Question', 'url': '/add_question', 'icon': 'help'}, 
        {'name': 'Add Exam Schedule', 'url': '/add_exam_schedule', 'icon': 'event'}, 
        {'name': 'Add Exam Result', 'url': '/add_exam_result', 'icon': 'poll'}, 
        {'name': 'Add Attendance', 'url': '/add_attendance', 'icon': 'check_circle'}, 
        {'name': 'Add Assignment', 'url': '/add_assignment', 'icon': 'assignment_turned_in'}, 
        {'name': 'Add Assignment Result', 'url': '/add_assignment_result', 'icon': 'assignment_returned'}, 
        {'name': 'Add Notice', 'url': '/add_notice', 'icon': 'announcement'}, 
        {'name': 'Add Event', 'url': '/add_event', 'icon': 'event_available'}, 
        # {'name': 'Add Gallery', 'url': '/add_gallery', 'icon': 'photo_library'}, 
        # {'name': 'Add Video', 'url': '/add_video', 'icon': 'video_library'}, 
        # {'name': 'Add Feedback', 'url': '/add_feedback', 'icon': 'feedback'}, 
        # {'name': 'Add Complaint', 'url': '/add_complaint', 'icon': 'report'}, 
        # {'name': 'Add Holiday', 'url': '/add_holiday', 'icon': 'beach_access'}, 
        {'name': 'Add Time Table', 'url': '/add_time_table', 'icon': 'schedule'}, 
        # {'name': 'Add Syllabus', 'url': '/add_syllabus', 'icon': 'description'}, 
        {'name': 'Add Result', 'url': '/add_result', 'icon': 'bar_chart'}, 
        # {'name': 'Add Fee', 'url': '/add_fee', 'icon': 'attach_money'}, 
        # {'name': 'Add Payment', 'url': '/add_payment', 'icon': 'payment'}, 
        # {'name': 'Add Library', 'url': '/add_library', 'icon': 'library_books'}, 
        # {'name': 'Add Hostel', 'url': '/add_hostel', 'icon': 'hotel'}, 
        # {'name': 'Add Transport', 'url': '/add_transport', 'icon': 'directions_bus'}, 
        # {'name': 'Add Canteen', 'url': '/add_canteen', 'icon': 'restaurant'}, 
        # {'name': 'Add Sports', 'url': '/add_sports', 'icon': 'sports_soccer'}, 
        # {'name': 'Add Club', 'url': '/add_club', 'icon': 'group'}, 
        # {'name': 'Add Activity', 'url': '/add_activity', 'icon': 'sports_kabaddi'}, 
        # {'name': 'Add Achievement', 'url': '/add_achievement', 'icon': 'emoji_events'}, 
        # {'name': 'Add Feedback', 'url': '/add_feedback', 'icon': 'feedback'}, 
        # {'name': 'Add Complaint', 'url': '/add_complaint', 'icon': 'report'}
        ]